steps:
    check:
        image: runmymind/docker-android-sdk:latest
        when:
          branch: main
          event: [push, pull_request, manual]
        commands:
          - ./gradlew build --stacktrace
          - mv app/build/outputs/apk/fcm/debug/app-fcm-debug.apk UP-Example-fcm.apk
          - mv app/build/outputs/apk/mainFlavor/debug/app-mainFlavor-debug.apk UP-Example-main.apk

    build:
        image: runmymind/docker-android-sdk:latest
        when:
          branch: main
          event: tag
        commands:
          - export RELEASE_STORE_FILE=$PWD/release-key.jks
          - echo $RELEASE_KEY | base64 -d > $RELEASE_STORE_FILE
          - ./gradlew -Psign assembleRelease --stacktrace
          - mv app/build/outputs/apk/fcm/release/app-fcm-release.apk UP-Example-fcm.apk
          - mv app/build/outputs/apk/mainFlavor/release/app-mainFlavor-release.apk UP-Example-main.apk
        environment:
          - RELEASE_KEY_ALIAS=unifiedpush
        secrets: [ release_key, release_store_password, release_key_password ]

    upload:
        image: codeberg.org/s1m/woodpecker-upload:latest
        when:
            branch: main
            event: [push, pull_request, tag, manual]
        settings:
            token:
                from_secret: codeberg_token
            file:
                - UP-Example-main.apk
                - UP-Example-fcm.apk
            fastlane: true
            package: true

